
ALTER TABLE quotations ADD COLUMN currency TEXT DEFAULT 'USD';
ALTER TABLE quotations ADD COLUMN subtotal REAL;
ALTER TABLE quotations ADD COLUMN sgst REAL DEFAULT 0;
ALTER TABLE quotations ADD COLUMN cgst REAL DEFAULT 0;
ALTER TABLE quotations ADD COLUMN igst REAL DEFAULT 0;
